language: julia

os:
  - linux

julia:
  - 1.2

before_script:
  - julia -e 'using Pkg; Pkg.add("Test")'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("SimpleSDMLayers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg; cd(Pkg.dir("SimpleSDMLayers")); include(joinpath("docs", "make.jl"))'
