language: julia

os:
  - linux

julia:
  - 1.2

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("SimpleSDMLayers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
