name: Bug Report
description: File a bug report - this is the type of issue to use if you are fairly sure something is going awfully wrong with the package.
title: "🐛 "
labels: ["bug", "needs-triage"]
assignees:
  - tpoisot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This is one of the most effective steps in making the project better.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? This is mostly important if the bug can be reproduced only when using data you are not able to share publicly.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Stacktrace
      description: Please copy and paste the stacktrace that give the error message.
      render: shell