name: To-do
description: This type of issues is mainly for the core development team, and is intended to collect notes about things to add or change to the package.
title: "✅ "
labels: ["todo", "needs-triage"]
assignees:
  - tpoisot
body:
  - type: input
    id: todo
    attributes:
      label: Description of the to-do item
      placeholder: add a brief description of the task here
    validations:
      required: true
  - type: textarea
    id: todo-more-info
    attributes:
      label: More information about the item
      placeholder: in particular, what parts of the package is it going to interact with
    validations:
      required: true